DROP TABLE IF EXISTS table_info;  

CREATE TABLE table_info (
ID INT AUTO_INCREMENT PRIMARY KEY ,
TABLE_NO VARCHAR(10),
SEATING_COUNT INT
);

--DROP SEQUENCE IF EXISTS HIBERNATE_SEQUENCE;  

--CREATE SEQUENCE HIBERNATE_SEQUENCE START WITH 110 INCREMENT BY 1;